// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Collections: typeof import('./src/components/pages/LandingPage/sections/Collections.vue')['default']
    Container: typeof import('./src/components/elements/Container.vue')['default']
    Decor: typeof import('./src/components/pages/LandingPage/sections/Decor.vue')['default']
    FurButton: typeof import('./src/components/elements/FurButton.vue')['default']
    FurFooter: typeof import('./src/components/pages/LandingPage/sections/FurFooter.vue')['default']
    FurNavbar: typeof import('./src/components/elements/FurNavbar.vue')['default']
    Hero: typeof import('./src/components/pages/LandingPage/sections/Hero.vue')['default']
    LandingPage: typeof import('./src/components/pages/LandingPage/LandingPage.vue')['default']
    Product: typeof import('./src/components/pages/LandingPage/sections/Product.vue')['default']
    ProductCard: typeof import('./src/components/elements/ProductCard.vue')['default']
    Subcribe: typeof import('./src/components/pages/LandingPage/sections/Subcribe.vue')['default']
  }
}

export {}
