// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Benefit: typeof import('./src/components/pages/LandingPage/sections/Benefit/index.vue')['default']
    BenefitItem: typeof import('./src/components/pages/LandingPage/sections/Benefit/BenefitItem.vue')['default']
    CollectionImage: typeof import('./src/components/elements/CollectionImage.vue')['default']
    CollectionItem: typeof import('./src/components/elements/CollectionItem.vue')['default']
    Collections: typeof import('./src/components/pages/LandingPage/sections/Collections.vue')['default']
    Container: typeof import('./src/components/elements/Container.vue')['default']
    Decor: typeof import('./src/components/pages/LandingPage/sections/Decor.vue')['default']
    FurButton: typeof import('./src/components/elements/FurButton.vue')['default']
    FurFooter: typeof import('./src/components/pages/LandingPage/sections/FurFooter.vue')['default']
    FurNavbar: typeof import('./src/components/elements/FurNavbar.vue')['default']
    Hero: typeof import('./src/components/pages/LandingPage/sections/Hero.vue')['default']
    LandingPage: typeof import('./src/components/pages/LandingPage/LandingPage.vue')['default']
    PlantCircle: typeof import('./src/components/elements/PlantCircle.vue')['default']
    PlantCircleButton: typeof import('./src/components/elements/PlantCircleButton.vue')['default']
    Product: typeof import('./src/components/pages/LandingPage/sections/Product.vue')['default']
    ProductCard: typeof import('./src/components/elements/ProductCard.vue')['default']
    Sections: typeof import('./src/components/pages/LandingPage/sections/index.vue')['default']
    Subcribe: typeof import('./src/components/pages/LandingPage/sections/Subcribe.vue')['default']
    UnsupportPlatform: typeof import('./src/components/elements/UnsupportPlatform.vue')['default']
  }
}

export {}
